### ISSUE TITLE
[doc] usage de "source" à l'ajout d'un lien

### ISSUE THREAD

**Issue by tetraf** [sebsauvage/Shaarli#149]
Dans l'URL d'ajout de lien il y a un argument "source" (souvent "source=bookmarklet") mais cette information ne semble pas être stockée dans le datastore.php ni mentionnée dans l'interface.

Quel est son rôle actuel ? Sinon, comment sera-t-il utilisé ?

**Comment by nodiscc** [comment]
@tetraf la réponse plus d'un an après:

Dans https://github.com/shaarli/Shaarli/blob/master/tpl/page.header.html:

```
{if="!empty($_GET['source']) && $_GET['source']=='bookmarklet'"}
{ignore} When called as a popup from bookmarklet, do not display menu. {/ignore}
{else}
```

Voila. Si source=bookmarklet, on n'affiche pas la barre d'outils/boutons.

Je pense que tu peux fermer cette issue.

**Comment by tetraf** [comment]
@nodiscc : Merci, ça pourrait peut-être être bien que cette information se retrouve dans le README ou dans le wiki. Bon après si les gens cherchent dans les tickets ils trouveront. Je ferme.

**Comment by nodiscc** [comment]
@tetraf Ca pourrait éventuellement être utile pour les développeurs. Ceci dit les autres paramètres POST ne sont pas documentés non plus. La doc de développement est dans le code donc ça ne me dérange pas de laisser tel quel. Si tu veux éditer la doc, le wiki est modifiable par tout le monde.

NB je parle du fork https://github.com/shaarli/Shaarli
