### ISSUE TITLE
Remove the annoying parameters added by facebook

### ISSUE THREAD

**Issue by alexisju** [sebsauvage/Shaarli#168]
Dans index.php, j'ai ajouté ceci pour nettoyer l'url des liens ouverts depuis facebook (ligne 1574 chez moi):

$i=strpos($url,'?fb_'); if ($i!==false) $url=substr($url,0,$i);

**Comment by alexisju** [comment]
J'utilise également d'autres filtres sur mon shaarli :

$i=strpos($url,'?__scoop'); if ($i!==false) $url=substr($url,0,$i);	
$i=strpos($url,'#tk.rss_all?'); if ($i!==false) $url=substr($url,0,$i);    
$i=strpos($url,'?utm_campaign='); if ($i!==false) $url=substr($url,0,$i); 
$i=strpos($url,'?utm_medium='); if ($i!==false) $url=substr($url,0,$i);

**Comment by nodiscc** [comment]
@alexisju J'aime l'idée de nettoyer les URLs, par contre pense que l'intégration à Shaarli n'est pas la meilleure solution; je serais même d'avis de retirer le nettoyage d'URL complètement (déjà pas mal de cleanup de fait ou en cours sur https://github.com/shaarli/Shaarli - fork communautaire) **mais** de fournir un userscript qui fasse le nettoyage directement au niveau du navigateur.

On pourrait facilement ajouter cet userscript à la doc et le publier sur https://monkeyguts.com/, https://openuserjs.org/, https://greasyfork.org/en avec un petit lien vers [Greasemonkey](https://addons.mozilla.org/fr/firefox/addon/greasemonkey/)

Peux tu ouvrir une issue sur https://github.com/shaarli/Shaarli/issues ?

**Comment by alexisju** [comment]
Oui, je comprends logique, mais l'externaliser complètement de shaarli risque d'être moins pratique pour l'utilisateur lambda. Or selon moi, c'est un fonctionnalité importante (personnellement, je déteste archiver des url avec ce genre de traqueurs)... Par ailleurs, même si le système actuel n'est pas parfait, il fonctionne pour une majorité des traqueurs que je rencontre; et ces traqueurs sont relativement stable dans le temps...

Bref, j'ouvre une nouvelle issue sur shaarli/shaarli :)

**Comment by nodiscc** [comment]
@alexisju je pense que tu peux fermer cette issue. Réglé dans https://github.com/shaarli/Shaarli/commit/01b8f52718f5136fb7de54e09b47ae4523aec9e8
