### ISSUE TITLE
Self in Atom (via reverse proxy)

### ISSUE THREAD

**Issue by FanchTheSystem** [sebsauvage/Shaarli#180]
Self link in showATOM function does not work on reverse proxy as REQUEST_URI contain the local path (not the server path)

``` php
$feed.='<link rel="self" href="'.htmlspecialchars(serverUrl().$_SERVER["REQUEST_URI"]).'" />';  
```

It is not good but it can be replaced by : 

``` php
$feed.='<link rel="self" href="'.htmlspecialchars(serverUrl().'/?do=atom').'" />';  
```

or 

``` php
$feed.='<link rel="self" href="'.htmlspecialchars(serverUrl().'/?'.$_SERVER["QUERY_STRING"]).'" />';
```

I think it is one of the only place where url can't be relative.

It is maybe better to use indexUrl() ...

**Comment by nodiscc** [comment]
@FanchTheSystem This is fixed in https://github.com/shaarli/Shaarli
