### ISSUE TITLE
Add history of last X tag sequence chosen in the tag field

### ISSUE THREAD

**Issue by s1dh** [sebsauvage/Shaarli#217]
In my workflow I open a new browser window per subject of interest  and I open as many tabs as needed during my searching session. The result is I often end this search session with dozen of interesting links I would like to bookmark . As all links could be tagged with almost the same 'keywords' , it would be great to press e.g. the down arrow in the tags field and have a scroll down list of the X last tag sequences chosen (X could be set as a parameter) and select the convenient tag sequence for all the links of the same window I want to bookmark. Of course I could add /remove one tag of the sequence If needed.

This way it would be quicker to save a bunch of links that deal with the same subject (keywords).

**Comment by nicolasdanelon** [comment]
This repo is dead. use this one [https://github.com/shaarli/Shaarli/](https://github.com/shaarli/Shaarli/)

**Comment by nodiscc** [comment]
Hi @s1dh can you close this issue? As you have [reported it](https://github.com/shaarli/Shaarli/issues/92) in the community fork repo and will likely not be fixed here, it helps keeping this bug tracker somewhat cleaner. Thanks
