### ISSUE TITLE
URL Encoding breaks anonymizer services

### ISSUE THREAD

**Issue by samadsajanlal** [sebsauvage/Shaarli#229]
Using latest stable shaarli available as of this post (2/15/2016)
WIthout HTTP_REFERER anonymization, shaarli works as intended. The example URL in this case will be http://imgur.com/wE0d3XU <- this is what is passed to my browser when I do not use an anonymizer, and I am able to see it just fine by clicking it from within Shaarli.

Using an anonymizer, the URL changes (it becomes encoded). For example, the same URL is encoded like this when used with "http://blankrefer.com/?" in configuration: http://blankrefer.com/?http%3A%2F%2Fi.imgur.com%2FwE0d3XU.jpg
I have noticed this encoding only occurs during anonymization.

Unfortunately, this procedure breaks functionality - it is no longer possible to visit the page without modifying the URL to remove the encoding. Many anonymizing services do not like receiving encoded URLs (blankrefer, anon.click, etc). Is it possible for an option to not encode the URL when passing to an anonymizer? I did not see any configuration options to prevent it.

I am using Firefox but it occurs in Chrome as well, both latest stable releases.

**Comment by ArthurHoaro** [comment]
Please reopen this in https://github.com/shaarli/Shaarli
