### ISSUE TITLE
writing to the datastore from console

### ISSUE THREAD

**Issue by electricflock** [sebsauvage/Shaarli#232]
hello all!

I have just started using Shaarli today on my self-hosted box and I am loving it! Everything I've been looking for, except one thing, which I believe I just need a point in the right direction.

I found the documentation for reading from the datastore, and I have come across this bit of code:
`php -r 'print(json_encode(unserialize(gzinflate(base64_decode(preg_replace("!.*/\* (.+) \*/.*!", "$1", file_get_contents("/opt/www/links/data/datastore.p hp")))))));' | jq .`

This works great! However, I will be setting up my server to parse the links and take action on select links. 

**I was wondering if it is possible to "reserialize/gzdeflate/base64_recode" the data after a parse, effectively I want to delete select notes after my machine has dealt with them**

I am by no means an advanced web/php dev, so if anyone has any suggestions or help it would be greatly appreciated!

**Comment by ArthurHoaro** [comment]
Hi @andrunie. This repo is unmaintained. Could you please open your issue in https://github.com/shaarli/Shaarli?

**Comment by electricflock** [comment]
thanks for letting me know, I will close this one and open it in the proper location.
