### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by k0nsl** [sebsauvage/Shaarli#234]
Hello Mr. Sauvage,

Do you intend to maintain this project or is it more or less abandoned? I actually just stumbled upon it today by mere coincidence and I think it's a really neat little application.

I haven't really looked through the code yet so I cannot judge whether it is safe to run this or not, seeing as it's rather old by today's standards. I will inspect it later tonight.

Anyway, good job and I hope you will continue working on it!

**Comment by ArthurHoaro** [comment]
Hi,
You should check out the community version at github.com/shaarli/Shaarli.

**Comment by k0nsl** [comment]
@ArthurHoaro: oh, I didn't know about the existence of that. That's great!
