### ISSUE TITLE
Tags are case sensitive 

### ISSUE THREAD

**Issue by Fl0rent** [sebsauvage/Shaarli#237]
Is it normal that in my tag cloud my tags are casesensitive

<img width="166" alt="capture d ecran 2016-09-16 16 25 37" src="https://cloud.githubusercontent.com/assets/1076038/18589366/b8d26bfc-7c2a-11e6-9cc6-7474c0903407.png">

And when I click on it, it's not. I see all my tags CSS + Css + css.
 is it normal?

**Comment by mro** [comment]
indeed, they are case sensitive. You can consolidate them via tools->rename from time to time.

**Comment by Fl0rent** [comment]
Yes I see that.
it's just because I import a lot of links from inboard, and it's a mess :-)
I gonna clean this!
