### ISSUE TITLE
[FR] Database storage

### ISSUE THREAD

**Issue by anayrat** [sebsauvage/Shaarli#239]
Hi,

It will be useful to add database (Postgres, mysql) support.

Do you plan to add this feature?

Thanks!

**Comment by lpefferkorn** [comment]
Hi,
I believe this is clearly against the KISS principle of Shaarli. What would be the benefits? 

Cheers,

**Comment by anayrat** [comment]
I suppose we'ill have better performance if you add lots of links?

**Comment by anayrat** [comment]
And search feature using indexes.

**Comment by mro** [comment]
@lpefferkorn yes, I think so, too.

@anayrat what is a lot? 20k+ fast enough http://sebsauvage.net/links/ ?

**Comment by anayrat** [comment]
Ok, I see, I'll try with the current version, thanks.
