### ISSUE TITLE
Remove an item from filtered list

### ISSUE THREAD

**Issue by sprnza** [sebsauvage/Shaarli#243]
Hi there!
Thank you for the great project!
I've stumbled upon a weird behavior and I think it's a bug. 

# Steps to reproduce

1. Filter a link list using a tag.
1. Try to delete any link
1. Get the filter resetted

**Comment by sprnza** [comment]
Oops, seems like I'm not able to reproduce it in Firefox. So the bug is Palemoon related only but I'll need to confirm this on an empty profile. I'll close the issie for now.

**Comment by nicolasdanelon** [comment]
there's a fork of shaarli check it out, https://github.com/shaarli/Shaarli

**Comment by sprnza** [comment]
@nicolasdanelon Oops. Thanks! I'm using the fork actually.
