### ISSUE TITLE
piwik support

### ISSUE THREAD

**Issue by jeekajoo** [sebsauvage/Shaarli#81]
Hi, do you have any plan to implement piwik? 
1) Add 2 parameters in /?do=configure screen :
- {$PIWIK_URL}
- {$IDSITE}

2) Add tracking code into the end of each page :
http://piwik.org/docs/javascript-tracking/#toc-where-can-i-find-the-piwik-tracking-code

I can try to make a pull request for it.
Thanks

**Comment by nodiscc** [comment]
Hi @jeekajoo there is a working plugin system that would allow you to do this in the shaarli/Shaarli fork, on this branch https://github.com/shaarli/Shaarli/tree/new-plugin-system. Discussion is at https://github.com/shaarli/Shaarli/issues/14.

Feel free to send pull requests on this branch if you want to add a Piwik plugin (basically you just have to add a footer plugin that takes thes 2 vars into account, look at the other plugins in `tpl/plugins/`) for examples.

I'm personnally not interested in working on it.

**Comment by jeekajoo** [comment]
actually I abandonned the idea of using piwik. everywhere
because I care about the privacy of my visitors as much I care about mine.

but thanks ;)
feel free to close the ticket if you want to.

**Comment by nodiscc** [comment]
@jeekajoo I don't have necessary rights to close this issue, can you do it?

I also agree that tracking serves no purpose except looking at pretty stats.
Server log analysis is enough for me to gather some stats and detect threats.
