### ISSUE TITLE
Reduce size of big thumbnails

### ISSUE THREAD

**Issue by tcitworld** [sebsauvage/Shaarli#91]
These type of pictures should definitely be reduced. Takes lots of place in the main page for nothing. http://liens.effingo.be/?3rUQqA
There must be a way to do this without doing direct modification of picture with GD.

**Comment by nodiscc** [comment]
@tcitworld do you have `php-gd` installed? Images should be resized to 120px width automatically (on your server, they aren't). Please check your config.

[function resizeImage()](https://github.com/shaarli/Shaarli/blob/master/index.php#L2563)

**Comment by tcitworld** [comment]
Whoho, asking me nearly two years later, I've changed server a few times, so I can't remember if that was the case.

**Comment by nodiscc** [comment]
@tcitworld you can check by verifying that your thumbnails do not exceed 120px in width. Can you close this issue if it's fixed for you?

**Comment by tcitworld** [comment]
I don't use Shaarli much anymore, so I'll close this issue.
